all:
	dmd editor.d \
		../../../arsd/web.d ../../../arsd/cgi.d ../../../arsd/jsvar.d ../../../arsd/dom.d ../../../arsd/characterencodings.d ../../../arsd/html.d \
		../../../arsd/color.d ../../../arsd/sha.d \
		-version=embedded_httpd
